<?php
declare(strict_types=1);
require_once __DIR__.'/config/config.php';require_once __DIR__.'/includes/site.php';
$slug=trim((string)($_GET['slug']??''));$project=null;
if($slug!==''){try{$s=db()->prepare('SELECT * FROM projects WHERE slug=? AND is_published=1 LIMIT 1');$s->execute([$slug]);$project=$s->fetch();}catch(Throwable $e){$project=null;}}
$esc=static fn($v):string=>htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');
if(!$project){http_response_code(404);$title='Case Study Not Found';}else{$title=$esc($project['title']??'Case Study').' | Case Study';}
$siteName=setting('site_name',APP_NAME);$metaDescription=$project?$esc($project['short_description']??''):setting('meta_description','');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?=$metaDescription?>"><title><?=$title?> | <?=$esc($siteName)?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="assets/css/style.css" rel="stylesheet"><style>.case-hero{padding:150px 0 90px;background:#07111f;color:#fff}.case-label{letter-spacing:.14em;text-transform:uppercase;font-size:.78rem;font-weight:800;color:#8ea4bd}.case-title{font-size:clamp(2.6rem,6vw,5rem);font-weight:800;line-height:1.02}.case-image{min-height:420px;border-radius:28px;background:#101d2d center/cover no-repeat;box-shadow:0 30px 80px rgba(0,0,0,.18)}.case-content{padding:90px 0}.case-content h2{font-weight:800;margin-bottom:18px}.case-content p{font-size:1.08rem;line-height:1.85;color:#536173}.case-meta{border-top:1px solid #dce2e8;border-bottom:1px solid #dce2e8;padding:28px 0;margin:35px 0}.case-meta strong{display:block;color:#101827}.case-cta{background:#07111f;color:#fff;border-radius:28px;padding:55px}.tag{display:inline-block;background:#edf2f7;border-radius:999px;padding:7px 13px;margin:4px;font-size:.85rem}</style></head><body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"><div class="container py-2"><a class="navbar-brand fw-bold" href="<?=htmlspecialchars(app_url())?>"><?=$esc($siteName)?></a><a href="<?=htmlspecialchars(app_url('index.php#projects'))?>" class="btn btn-outline-light btn-sm ms-auto">Back to Portfolio</a></div></nav>
<?php if(!$project): ?><main class="case-hero"><div class="container"><div class="case-label">404 — CASE STUDY</div><h1 class="case-title mt-3">Case study not found.</h1><p class="lead text-white-50 mt-4">The project may have been unpublished, removed, or the link is incorrect.</p><a class="btn btn-light mt-3" href="<?=htmlspecialchars(app_url('index.php#projects'))?>">View Projects</a></div></main><?php else: ?>
<header class="case-hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><div class="case-label"><?=$esc($project['category']??'Project')?></div><h1 class="case-title mt-3"><?=$esc($project['title']??'')?></h1><p class="lead text-white-50 mt-4"><?=$esc($project['short_description']??'')?></p><div class="d-flex flex-wrap gap-2 mt-4"><?php if(!empty($project['live_url'])):?><a class="btn btn-light" href="<?=$esc($project['live_url'])?>" target="_blank" rel="noopener">Visit Live Project <i class="bi bi-arrow-up-right"></i></a><?php endif;if(!empty($project['github_url'])):?><a class="btn btn-outline-light" href="<?=$esc($project['github_url'])?>" target="_blank" rel="noopener">View Code <i class="bi bi-github"></i></a><?php endif;?></div></div><div class="col-lg-5"><div class="case-image" <?php if(!empty($project['image'])):?>style="background-image:url('<?=$esc($project['image'])?>')"<?php endif;?>></div></div></div></div></header>
<main class="case-content"><div class="container"><div class="case-meta"><div class="row g-4"><div class="col-md-4"><strong>Category</strong><span><?=$esc($project['category']??'')?></span></div><div class="col-md-4"><strong>Technologies</strong><span><?=$esc($project['technologies']??'Custom Web Solution')?></span></div><div class="col-md-4"><strong>Project</strong><span><?=$esc($project['title']??'')?></span></div></div></div><div class="row g-5"><div class="col-lg-8"><section class="mb-5"><div class="case-label text-dark">01 — THE CHALLENGE</div><h2><?=$esc($project['challenge']?'The Challenge':'Project Overview')?></h2><p><?=nl2br($esc($project['challenge']?:$project['short_description']))?></p></section><section class="mb-5"><div class="case-label text-dark">02 — THE SOLUTION</div><h2>How we approached it</h2><p><?=nl2br($esc($project['solution']?:'We designed and developed a focused digital solution around the project requirements, combining usability, responsive design and maintainable technology.'))?></p></section></div><div class="col-lg-4"><div class="p-4 bg-light rounded-4"><div class="case-label text-dark">TECH STACK</div><div class="mt-3"><?php foreach(preg_split('/[,|]+/',(string)($project['technologies']??'')) as $tech):if(trim($tech)):?><span class="tag"><?=$esc(trim($tech))?></span><?php endif;endforeach;?></div></div></div></div><div class="case-cta mt-5"><div class="case-label">READY FOR YOUR NEXT PROJECT?</div><h2 class="display-6 fw-bold mt-2">Let's build something that moves your business forward.</h2><a href="<?=htmlspecialchars(app_url('index.php#contact'))?>" class="btn btn-light mt-3">Start a Project <i class="bi bi-arrow-up-right"></i></a></div></div></main><?php endif; ?><footer class="bg-dark text-white-50 py-4"><div class="container small">© <?=date('Y')?> <?=$esc($siteName)?></div></footer></body></html>