<?php
declare(strict_types=1);
require_once __DIR__.'/config/config.php';
require_once __DIR__.'/config/database.php';
require_once __DIR__.'/includes/mailer.php';
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Location: '.app_url('index.php#contact'));exit;}
$clean=static fn(string $v):string=>trim(preg_replace('/\s+/u',' ',$v));
$name=$clean((string)($_POST['name']??''));$email=trim((string)($_POST['email']??''));$phone=$clean((string)($_POST['phone']??''));$company=$clean((string)($_POST['company']??''));$service=$clean((string)($_POST['service']??''));$budget=$clean((string)($_POST['budget']??''));$timeline=$clean((string)($_POST['timeline']??''));$message=trim((string)($_POST['message']??''));$errors=[];
if($name===''||mb_strlen($name)>180)$errors[]='Please provide your name.';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||mb_strlen($email)>255)$errors[]='Please provide a valid email address.';if($message===''||mb_strlen($message)>10000)$errors[]='Please tell us about your project.';
if($errors){http_response_code(422);?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enquiry Error</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-5" style="max-width:700px"><div class="alert alert-danger"><h1 class="h5">Please check your enquiry</h1><ul class="mb-0"><?php foreach($errors as $error):?><li><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></li><?php endforeach;?></ul></div><a href="<?=htmlspecialchars(app_url('index.php#contact'),ENT_QUOTES,'UTF-8')?>" class="btn btn-dark">Go back</a></main></body></html><?php exit;}
try{$stmt=db()->prepare('INSERT INTO leads (name,email,phone,company,service,budget,timeline,message,source) VALUES (?,?,?,?,?,?,?,?,?)');$stmt->execute([$name,$email,$phone?:null,$company?:null,$service?:null,$budget?:null,$timeline?:null,$message,'website']);$lead=['id'=>(int)db()->lastInsertId(),'name'=>$name,'email'=>$email,'phone'=>$phone,'company'=>$company,'service'=>$service,'budget'=>$budget,'timeline'=>$timeline,'message'=>$message];send_lead_notification($lead);send_lead_confirmation($lead);header('Location: '.app_url('thank-you.php'));exit;}catch(Throwable $e){http_response_code(500);?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Unable to Send</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><main class="container py-5"><div class="alert alert-danger">We couldn't save your enquiry right now. Please try again shortly.</div><a href="<?=htmlspecialchars(app_url('index.php#contact'),ENT_QUOTES,'UTF-8')?>" class="btn btn-dark">Return to website</a></main></body></html><?php exit;}