<?php
require_once __DIR__ . '/../config/config.php';
$title = 'Digital Banking Platform';
$category = 'FinTech / Web Application';
$summary = 'A secure, database-driven digital banking platform designed around customer account management, transactions, transfers, notifications and administrative operations.';
$challenge = 'The project required a structured digital banking experience capable of supporting multiple customer-facing operations while giving administrators visibility and control over core activities. The system also needed a responsive interface that could work across desktop and mobile devices.';
$solution = 'The solution was structured as a modular web application with authentication, account workflows, transaction handling, notifications and administrative functionality. The interface was designed with Bootstrap for responsive presentation, while the backend and data layer were organized around PHP and MySQL.';
$features = ['Customer authentication and account access','Account and profile management','Transaction and transfer workflows','Notifications and operational events','Administrative management','Responsive Bootstrap interface','Database-backed records and reporting foundation'];
$technology = ['PHP','MySQL','Bootstrap 5','JavaScript','REST/API integration'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?= htmlspecialchars($summary) ?>"><title><?= htmlspecialchars($title) ?> | <?= APP_NAME ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><style>:root{--navy:#07111f;--navy2:#0b1628;--blue:#4da3ff;--gold:#d8b36a}body{font-family:Inter,sans-serif;background:#f5f7fa;color:#18283d}.hero{background:radial-gradient(circle at 80% 20%,rgba(77,163,255,.15),transparent 30%),var(--navy);color:#fff;padding:150px 0 100px}.eyebrow{text-transform:uppercase;letter-spacing:.15em;color:var(--blue);font-size:.72rem;font-weight:800}.hero h1{font-family:Manrope,sans-serif;font-size:clamp(3rem,7vw,6rem);font-weight:800;letter-spacing:-.05em}.hero p{max-width:800px;color:#b8c5d6;line-height:1.8;font-size:1.08rem}.section{padding:90px 0}.label{color:#2278d2;font-size:.72rem;font-weight:800;letter-spacing:.14em}.section h2{font-family:Manrope,sans-serif;font-weight:800;letter-spacing:-.035em}.card-clean{background:#fff;border:1px solid #e1e7ee;border-radius:20px;padding:28px;height:100%;box-shadow:0 15px 50px rgba(12,28,50,.06)}.feature-list{list-style:none;padding:0}.feature-list li{padding:13px 0;border-bottom:1px solid #e8edf2}.feature-list i{color:#2278d2;margin-right:10px}.tech{display:flex;flex-wrap:wrap;gap:10px}.tech span{background:#eaf3fc;color:#1d6fbf;border-radius:999px;padding:9px 13px;font-size:.8rem;font-weight:700}.back{color:#fff;text-decoration:none}.cta{background:var(--navy2);color:#fff;border-radius:24px;padding:50px}.btn-brand{background:linear-gradient(135deg,#4da3ff,#2278d2);border:0;color:#fff;font-weight:700;padding:12px 20px;border-radius:10px}.btn-brand:hover{color:#fff}.footer{background:#050d18;color:#718198;padding:30px 0}@media(max-width:767px){.hero{padding:125px 0 80px}.section{padding:65px 0}}</style></head><body>
<header class="hero"><div class="container"><a class="back d-inline-block mb-5" href="../index.php#projects"><i class="bi bi-arrow-left"></i> Back to Projects</a><div class="eyebrow mb-3"><?= htmlspecialchars($category) ?></div><h1><?= htmlspecialchars($title) ?></h1><p class="mt-4"><?= htmlspecialchars($summary) ?></p></div></header>
<main><section class="section"><div class="container"><div class="row g-5"><div class="col-lg-7"><div class="label mb-3">THE CHALLENGE</div><h2 class="display-6 mb-4">Building a reliable digital banking experience.</h2><p class="lead" style="line-height:1.8;color:#52657a"><?= htmlspecialchars($challenge) ?></p></div><div class="col-lg-5"><div class="card-clean"><div class="label mb-3">PROJECT TYPE</div><h3>FinTech Web Application</h3><p class="mb-0" style="color:#68788c;line-height:1.7">A structured customer and operations platform with a responsive interface and database-backed workflows.</p></div></div></div></div></section>
<section class="section bg-white"><div class="container"><div class="row g-5"><div class="col-lg-7"><div class="label mb-3">THE SOLUTION</div><h2 class="display-6 mb-4">A modular platform built around banking workflows.</h2><p style="color:#68788c;line-height:1.8"><?= htmlspecialchars($solution) ?></p></div><div class="col-lg-5"><div class="card-clean"><div class="label mb-3">KEY CAPABILITIES</div><ul class="feature-list mb-0"><?php foreach($features as $feature): ?><li><i class="bi bi-check-circle-fill"></i><?= htmlspecialchars($feature) ?></li><?php endforeach; ?></ul></div></div></div></div></section>
<section class="section"><div class="container"><div class="label mb-3">TECHNOLOGY</div><h2 class="display-6 mb-4">Technology stack</h2><div class="tech"><?php foreach($technology as $item): ?><span><?= htmlspecialchars($item) ?></span><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><div class="cta"><div class="label mb-3">BUILD YOUR DIGITAL PLATFORM</div><h2 class="display-6">Need a custom business application?</h2><p class="mt-3" style="color:#aebdce;max-width:700px;line-height:1.8">Distinguished Web Services can design and develop a database-driven platform around your business processes, customers and operational requirements.</p><a href="../index.php#contact" class="btn btn-brand mt-3">Start a Project <i class="bi bi-arrow-up-right"></i></a></div></div></section></main><footer class="footer"><div class="container">© <?= date('Y') ?> <?= APP_NAME ?> · Web Development · Digital Marketing · Automation</div></footer></body></html>
