<?php
require_once __DIR__ . '/../config/config.php';
$title='Logistics Management Platform'; $category='Logistics / Business Platform';
$summary='A digital operations platform designed to organize customers, logistics workflows, deliveries and operational reporting in one connected environment.';
$challenge='Logistics businesses often have to coordinate customers, orders, delivery activities and operational updates across multiple channels. The objective was to create a centralized digital workflow that could make those activities easier to manage and provide a foundation for future integrations.';
$solution='The platform was designed around core logistics entities and workflows, with a responsive interface for day-to-day operations. A database-backed architecture provides a structured foundation for customer records, logistics activities, delivery information and administrative oversight.';
$features=['Customer and business record management','Logistics workflow management','Order and delivery information','Administrative controls','Operational reporting foundation','Responsive web interface','API-ready architecture for future integrations'];
$technology=['PHP / Web Application','MySQL','Bootstrap 5','JavaScript','REST/API integration'];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="<?= htmlspecialchars($summary) ?>"><title><?= htmlspecialchars($title) ?> | <?= APP_NAME ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet"><style>:root{--navy:#07111f;--navy2:#0b1628;--blue:#4da3ff}body{font-family:Inter,sans-serif;background:#f5f7fa;color:#18283d}.hero{background:radial-gradient(circle at 80% 20%,rgba(77,163,255,.15),transparent 30%),var(--navy);color:#fff;padding:150px 0 100px}.eyebrow,.label{color:#4da3ff;text-transform:uppercase;letter-spacing:.14em;font-size:.72rem;font-weight:800}.hero h1,h2{font-family:Manrope,sans-serif;font-weight:800;letter-spacing:-.045em}.hero h1{font-size:clamp(3rem,7vw,6rem)}.hero p{max-width:800px;color:#b8c5d6;line-height:1.8;font-size:1.08rem}.back{color:#fff;text-decoration:none}.section{padding:90px 0}.card-clean{background:#fff;border:1px solid #e1e7ee;border-radius:20px;padding:28px;height:100%;box-shadow:0 15px 50px rgba(12,28,50,.06)}.feature-list{list-style:none;padding:0}.feature-list li{padding:13px 0;border-bottom:1px solid #e8edf2}.feature-list i{color:#2278d2;margin-right:10px}.tech{display:flex;flex-wrap:wrap;gap:10px}.tech span{background:#eaf3fc;color:#1d6fbf;border-radius:999px;padding:9px 13px;font-size:.8rem;font-weight:700}.cta{background:var(--navy2);color:#fff;border-radius:24px;padding:50px}.btn-brand{background:linear-gradient(135deg,#4da3ff,#2278d2);border:0;color:#fff;font-weight:700;padding:12px 20px;border-radius:10px}.footer{background:#050d18;color:#718198;padding:30px 0}@media(max-width:767px){.hero{padding:125px 0 80px}.section{padding:65px 0}}</style></head><body>
<header class="hero"><div class="container"><a class="back d-inline-block mb-5" href="../index.php#projects"><i class="bi bi-arrow-left"></i> Back to Projects</a><div class="eyebrow mb-3"><?= htmlspecialchars($category) ?></div><h1><?= htmlspecialchars($title) ?></h1><p class="mt-4"><?= htmlspecialchars($summary) ?></p></div></header>
<main><section class="section"><div class="container"><div class="row g-5"><div class="col-lg-7"><div class="label mb-3">THE CHALLENGE</div><h2 class="display-6 mb-4">Connecting logistics operations in one digital workflow.</h2><p class="lead" style="line-height:1.8;color:#52657a"><?= htmlspecialchars($challenge) ?></p></div><div class="col-lg-5"><div class="card-clean"><div class="label mb-3">PROJECT TYPE</div><h3>Logistics Management</h3><p style="color:#68788c;line-height:1.7" class="mb-0">A business operations platform designed to give teams a central place to manage logistics activities.</p></div></div></div></div></section>
<section class="section bg-white"><div class="container"><div class="row g-5"><div class="col-lg-7"><div class="label mb-3">THE SOLUTION</div><h2 class="display-6 mb-4">A centralized operations platform.</h2><p style="color:#68788c;line-height:1.8"><?= htmlspecialchars($solution) ?></p></div><div class="col-lg-5"><div class="card-clean"><div class="label mb-3">KEY CAPABILITIES</div><ul class="feature-list mb-0"><?php foreach($features as $feature): ?><li><i class="bi bi-check-circle-fill"></i><?= htmlspecialchars($feature) ?></li><?php endforeach; ?></ul></div></div></div></div></section>
<section class="section"><div class="container"><div class="label mb-3">TECHNOLOGY</div><h2 class="display-6 mb-4">Technology stack</h2><div class="tech"><?php foreach($technology as $item): ?><span><?= htmlspecialchars($item) ?></span><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><div class="cta"><div class="label mb-3">DIGITAL OPERATIONS</div><h2 class="display-6">Ready to digitize your workflow?</h2><p class="mt-3" style="color:#aebdce;max-width:700px;line-height:1.8">We build custom systems that turn manual business processes into structured digital workflows.</p><a href="../index.php#contact" class="btn btn-brand mt-3">Discuss Your Project <i class="bi bi-arrow-up-right"></i></a></div></div></section></main><footer class="footer"><div class="container">© <?= date('Y') ?> <?= APP_NAME ?> · Web Development · Digital Marketing · Automation</div></footer></body></html>
