<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(403);exit('CLI only.');}
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../config/mailer.php';
$db=db();$settings=$db->query('SELECT * FROM crm_automation_settings WHERE id=1')->fetch();if(!$settings||!(int)$settings['enabled']){echo "CRM automation disabled.\n";exit;}
$log=function(?int $lead,string $type,string $message,string $status='success')use($db){$s=$db->prepare('INSERT INTO automation_logs (lead_id,event_type,message,status) VALUES (?,?,?,?)');$s->execute([$lead,$type,$message,$status]);};
$templateByType=['initial'=>'initial_followup','proposal'=>'proposal_followup','no_response'=>'no_response','closing'=>'closing_followup','reengagement'=>'no_response'];$maxAttempts=3;
if((int)$settings['auto_score']){$leads=$db->query("SELECT * FROM leads WHERE status NOT IN ('won','lost')")->fetchAll();foreach($leads as $l){$score=0;$reasons=[];$budget=strtolower((string)$l['budget']);$timeline=strtolower((string)$l['timeline']);if($l['service']){$score+=15;$reasons[]='Service selected';}if($l['company']){$score+=10;$reasons[]='Company supplied';}if($l['phone']){$score+=10;$reasons[]='Phone supplied';}if(strlen((string)$l['message'])>=100){$score+=15;$reasons[]='Detailed project brief';}if(preg_match('/urgent|asap|immediately|this week|1 week|2 weeks/i',$timeline)){$score+=20;$reasons[]='Urgent timeline';}if(preg_match('/5000|10000|15000|20000|25000|50000|100000|200000|500000|1000000/i',$budget)){$score+=20;$reasons[]='Higher budget indicated';}if($l['status']==='proposal'){$score+=10;$reasons[]='Proposal stage';}$temperature=$score>=70?'hot':($score>=40?'warm':'cold');$s=$db->prepare('INSERT INTO lead_scores (lead_id,score,temperature,reasons) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE score=VALUES(score),temperature=VALUES(temperature),reasons=VALUES(reasons),calculated_at=CURRENT_TIMESTAMP');$s->execute([(int)$l['id'],$score,$temperature,implode('; ',$reasons)]);$priority=$score>=70?'high':($score>=40?'normal':'low');if($priority!==$l['priority']){$db->prepare('UPDATE leads SET priority=? WHERE id=?')->execute([$priority,$l['id']]);$log((int)$l['id'],'lead_score','Lead scored '.$score.' ('.$temperature.') and priority set to '.$priority);}}}
$leads=$db->query("SELECT * FROM leads WHERE status NOT IN ('won','lost') AND follow_up_at IS NULL ORDER BY created_at ASC")->fetchAll();foreach($leads as $l){$created=strtotime((string)$l['created_at']);if((time()-$created)/3600 >= (int)$settings['initial_followup_hours']){$at=date('Y-m-d H:i:s',time()+((int)$settings['reminder_hours']*3600));$s=$db->prepare("INSERT INTO lead_followups (lead_id,followup_type,scheduled_at,subject,body,next_attempt_at) VALUES (?, 'initial', ?, ?, ?, ?)");$s->execute([(int)$l['id'],$at,'Initial follow-up','Initial follow-up for '.$l['name'],$at]);$db->prepare('UPDATE leads SET follow_up_at=? WHERE id=?')->execute([$at,$l['id']]);$log((int)$l['id'],'followup_scheduled','Initial follow-up scheduled for '.$at);}}
$due=$db->query("SELECT f.*,l.name,l.email,l.phone,l.service,l.company FROM lead_followups f JOIN leads l ON l.id=f.lead_id WHERE f.status='pending' AND COALESCE(f.next_attempt_at,f.scheduled_at)<=NOW() AND l.status NOT IN ('won','lost') ORDER BY COALESCE(f.next_attempt_at,f.scheduled_at) ASC LIMIT 100")->fetchAll();
foreach($due as $f){$leadId=(int)$f['lead_id'];$attempt=(int)$f['attempt_count']+1;$type=(string)$f['followup_type'];$templateKey=$templateByType[$type]??null;$emailSent=false;$error='Email not sent or template unavailable';
if($templateKey && filter_var($f['email'],FILTER_VALIDATE_EMAIL)){$ts=$db->prepare('SELECT * FROM email_templates WHERE template_key=? AND is_active=1 LIMIT 1');$ts->execute([$templateKey]);$template=$ts->fetch();if($template){$vars=['{{client_name}}'=>(string)$f['name'],'{{company}}'=>(string)($f['company']??''),'{{service}}'=>(string)$f['service'],'{{estimated_value}}'=>'','{{website_url}}'=>defined('APP_URL')?APP_URL:''];$subject=strtr((string)$template['subject'],$vars);$body=strtr((string)$template['body_html'],$vars);$ins=$db->prepare("INSERT INTO email_logs (lead_id,template_id,recipient_email,subject,status) VALUES (?,?,?,?, 'queued')");$ins->execute([$leadId,(int)$template['id'],$f['email'],$subject]);$emailLogId=(int)$db->lastInsertId();$result=send_smtp_email($f['email'],$subject,$body);if($result['success']){$db->prepare("UPDATE email_logs SET status='sent',sent_at=NOW() WHERE id=?")->execute([$emailLogId]);$db->prepare('INSERT INTO lead_activities (lead_id,activity_type,subject,description) VALUES (?,?,?,?)')->execute([$leadId,'email',$subject,'Automated CRM follow-up email sent to '.$f['email']]);$emailSent=true;}else{$error=$result['error'];$db->prepare("UPDATE email_logs SET status='failed',error_message=? WHERE id=?")->execute([$error,$emailLogId]);}}}
if($emailSent){$log($leadId,'followup_email_sent','Automated follow-up email sent on attempt '.$attempt.'.');$db->prepare("UPDATE lead_followups SET status='sent',attempt_count=?,last_attempt_at=NOW(),sent_at=NOW(),next_attempt_at=NULL,error_message=NULL WHERE id=?")->execute([$attempt,(int)$f['id']]);}else{$log($leadId,'email_failed','Automated follow-up attempt '.$attempt.' failed: '.$error,'error');if($attempt < $maxAttempts){$delayHours=pow(2,$attempt);$next=date('Y-m-d H:i:s',time()+($delayHours*3600));$db->prepare("UPDATE lead_followups SET attempt_count=?,last_attempt_at=NOW(),next_attempt_at=?,error_message=?,status='pending' WHERE id=?")->execute([$attempt,$next,$error,(int)$f['id']]);$db->prepare('INSERT INTO lead_activities (lead_id,activity_type,subject,description) VALUES (?,?,?,?)')->execute([$leadId,'follow_up','Automated follow-up retry scheduled','Attempt '.$attempt.' failed. Next retry: '.$next]);}else{$db->prepare("UPDATE lead_followups SET attempt_count=?,last_attempt_at=NOW(),next_attempt_at=NULL,error_message=?,status='failed' WHERE id=?")->execute([$attempt,$error,(int)$f['id']]);$db->prepare('INSERT INTO lead_activities (lead_id,activity_type,subject,description) VALUES (?,?,?,?)')->execute([$leadId,'follow_up','Automated follow-up failed','Maximum email attempts reached. Manual follow-up required.']);}}
$db->prepare('UPDATE leads SET follow_up_at=NULL WHERE id=? AND follow_up_at<=NOW()')->execute([$leadId]);}
echo 'CRM automation completed: '.date('Y-m-d H:i:s')."\n";