<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/includes/auth.php';

$stats = [
 'projects' => (int)db()->query('SELECT COUNT(*) FROM projects')->fetchColumn(),
 'services' => (int)db()->query('SELECT COUNT(*) FROM services')->fetchColumn(),
 'messages' => (int)db()->query("SELECT COUNT(*) FROM messages WHERE status='new'")->fetchColumn(),
 'testimonials' => (int)db()->query('SELECT COUNT(*) FROM testimonials')->fetchColumn(),
];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard | <?= htmlspecialchars(APP_NAME) ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand fw-bold" href="dashboard.php">Distinguished Web Services</a><div class="d-flex align-items-center gap-3 text-white"><span><?= htmlspecialchars((string)($_SESSION['admin_name'] ?? 'Administrator')) ?></span><a class="btn btn-outline-light btn-sm" href="logout.php">Logout</a></div></div></nav><main class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h2 fw-bold mb-1">Admin Dashboard</h1><p class="text-muted mb-0">Manage your portfolio content and enquiries.</p></div></div><div class="row g-4"><div class="col-md-6 col-xl-3"><div class="card border-0 shadow-sm"><div class="card-body"><i class="bi bi-briefcase fs-2"></i><div class="display-6 fw-bold mt-2"><?= $stats['projects'] ?></div><div class="text-muted">Projects</div><a href="projects.php" class="stretched-link">Manage</a></div></div></div><div class="col-md-6 col-xl-3"><div class="card border-0 shadow-sm"><div class="card-body"><i class="bi bi-grid fs-2"></i><div class="display-6 fw-bold mt-2"><?= $stats['services'] ?></div><div class="text-muted">Services</div><a href="services.php" class="stretched-link">Manage</a></div></div></div><div class="col-md-6 col-xl-3"><div class="card border-0 shadow-sm"><div class="card-body"><i class="bi bi-envelope fs-2"></i><div class="display-6 fw-bold mt-2"><?= $stats['messages'] ?></div><div class="text-muted">New Messages</div><a href="messages.php" class="stretched-link">View</a></div></div></div><div class="col-md-6 col-xl-3"><div class="card border-0 shadow-sm"><div class="card-body"><i class="bi bi-chat-quote fs-2"></i><div class="display-6 fw-bold mt-2"><?= $stats['testimonials'] ?></div><div class="text-muted">Testimonials</div><a href="testimonials.php" class="stretched-link">Manage</a></div></div></div></div></main></body></html>