<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/config.php'; require_once __DIR__ . '/../config/database.php'; require_once __DIR__ . '/includes/auth.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
 $action=$_POST['action']??''; $id=(int)($_POST['id']??0);
 if ($action==='delete' && $id) { db()->prepare('DELETE FROM projects WHERE id=?')->execute([$id]); header('Location: projects.php'); exit; }
 if ($action==='toggle' && $id) { db()->prepare('UPDATE projects SET is_published=1-is_published WHERE id=?')->execute([$id]); header('Location: projects.php'); exit; }
}
$projects=db()->query('SELECT * FROM projects ORDER BY is_featured DESC, created_at DESC')->fetchAll();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Projects | Admin</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><nav class="navbar navbar-dark bg-dark"><div class="container"><a class="navbar-brand" href="dashboard.php">Distinguished Web Services</a><a class="btn btn-outline-light btn-sm" href="logout.php">Logout</a></div></nav><main class="container py-5"><div class="d-flex justify-content-between align-items-center mb-4"><h1 class="h2">Projects</h1><a href="project-form.php" class="btn btn-primary">Add Project</a></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Project</th><th>Category</th><th>Featured</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($projects as $p): ?><tr><td><strong><?=htmlspecialchars($p['title'])?></strong><div class="small text-muted"><?=htmlspecialchars($p['slug'])?></div></td><td><?=htmlspecialchars($p['category'])?></td><td><?=((int)$p['is_featured']?'Yes':'No')?></td><td><span class="badge <?=((int)$p['is_published']?'text-bg-success':'text-bg-secondary')?>"><?=((int)$p['is_published']?'Published':'Draft')?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="project-form.php?id=<?=$p['id']?>">Edit</a><form method="post" class="d-inline"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn btn-sm btn-outline-secondary">Toggle</button></form><form method="post" class="d-inline" onsubmit="return confirm('Delete this project?')"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr><?php endforeach; if(!$projects): ?><tr><td colspan="5" class="text-center text-muted py-5">No projects yet.</td></tr><?php endif; ?></tbody></table></div></div></main></body></html>